all:
  hosts:
    pve.chk.no:
      ansible_host: pve.chk.no
      ansible_connection: ssh
      ansible_user: root
      ansible_port: 22
      ansible_ssh_private_key_file: /home/christian/.ssh/id_rsa
    docker.chk.no:
      ansible_host: docker.chk.no
      ansible_connection: ssh
      ansible_user: christian
      ansible_port: 22
      ansible_ssh_private_key_file: /home/christian/.ssh/id_rsa
      apps:
        - transmission_openvpn

