all:
  hosts:
    pve.chk.no:
      ansible_host: pve.chk.no
      ansible_connection: ssh
      ansible_user: root
      ansible_port: 22
      ansible_ssh_private_key_file: /home/christian/.ssh/id_rsa
    docker.chk.no:
      ansible_host: docker.chk.no
      ansible_connection: ssh
      ansible_user: christian
      ansible_port: 22
      ansible_ssh_private_key_file: /home/christian/.ssh/id_rsa
      apps:
        - transmission_openvpn
    tailnet.chk.no:
      ansible_host: 192.168.1.20
      ansible_connection: ssh
      ansible_user: root
      ansible_port: 22
      StrictHostKeyChecking: no
      UserKnownHostsFile: /dev/null
      ansible_ssh_private_key_file: /home/christian/.ssh/id_rsa
      ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'
    samba.chk.no:
      ansible_host: 192.168.1.30
      ansible_connection: ssh
      ansible_user: root
      ansible_port: 22
      StrictHostKeyChecking: no
      UserKnownHostsFile: /dev/null
      ansible_ssh_private_key_file: /home/christian/.ssh/id_rsa
      ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'
    docker.chk.no:
      ansible_host: 192.168.1.40
      ansible_connection: ssh
      ansible_user: debian
      ansible_port: 22
      StrictHostKeyChecking: no
      UserKnownHostsFile: /dev/null
      ansible_ssh_private_key_file: /home/christian/.ssh/id_rsa
      ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'

