- name: Ensure enterprise repo file is not present
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/pve-enterprise.list
    state: absent

- name: Ensure ceph enterprise repo file is not present
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/ceph.list
    state: absent

- name: Add No Subscription Repository
  ansible.builtin.apt_repository:
    repo: deb http://download.proxmox.com/debian/pve {{ ansible_distribution_release }} pve-no-subscription
    filename: pve-no-subscription
    state: present
