- name: Update grub
  ansible.builtin.command: update-grub
  changed_when: false

- name: Update initramfs
  ansible.builtin.command: update-initramfs -u
  changed_when: false

- name: Reboot
  ansible.builtin.reboot:
    msg: "IOUMMU Updated, rebooting machine!"
