version: 3.7.1
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.chk.no`)"
      - "traefik.http.routers.jellyfin.entrypoints=websecure"
      - "traefik.http.routers.jellyfin.tls.certresolver=le"
    group_add:
      - {{ render_group }} # getent group render | cut -d: -f3
    environment:
      - PUID=0 
      - PGID=0 
      - JELLYFIN_PublishedServerUrl=http://jellyfin.chk.no
    volumes:
      - /home/debian/jellyfin/config:/config
      - /home/debian/jellyfin/cache:/cache
      - type: bind
        source: /media
        target: /media
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    restart: 'unless-stopped'
