- name: Check if VM exists
  ansible.builtin.shell:
    cmd: qm list | grep debian12-cloudinit
  register: vm_result
  changed_when: false
  ignore_errors: true


- name: Get cloud init ready template
  ansible.builtin.get_url:
    url: https://cloud.debian.org/images/cloud/bookworm/latest/debian-12-generic-amd64.qcow2
    dest: /tmp/debian-12-generic.qcow2
    checksum: sha512:c58d50f583d63af0243957ce1378536329e6ae8226f23413d50417464d44d809427eb89c4941685d1d408f1f44ff61746abb033f4180e30d4f70e7d974f3fe8d
    mode: '0600'

- name: Install packages
  ansible.builtin.apt:
    name: libguestfs-tools
    update_cache: true

- name: Create and configure VM # noqa command-instead-of-module
  ansible.builtin.shell: |
   virt-customize -a /tmp/debian-12-generic.qcow2 --install qemu-guest-agent
   virt-customize -a focal-server-cloudimg-amd64.img --run-command "sed -i 's/.*PasswordAuthentication.*/PasswordAuthentication yes/g' /etc/ssh/sshd_config"
   qm create 9000 --name debian12-cloudinit --net0 virtio,bridge=vmbr0 --scsihw virtio-scsi-pci --machine q35
   qm set 9000 --scsi0 vmpool:0,discard=on,ssd=1,format=qcow2,import-from=/tmp/debian-12-generic.qcow2
   qm disk resize 9000 scsi0 8G
   qm set 9000 --boot order=scsi0
   qm set 9000 --cpu host --cores 2 --memory 2048
   qm set 9000 --bios ovmf --efidisk0 vmpool:1,format=qcow2,efitype=4m,pre-enrolled-keys=1
   qm set 9000 --ide2 local-lvm:cloudinit
   qm set 9000 --agent enabled=1
   qm template 9000
  changed_when: false
  when:
    - vm_result.rc != 0
