- name: Add cmdline default
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT='
    # Use C1 instead of C1E c-state, turn off hyperthreading, disable all optional CPU mitigations, turn on intel IOMMU, pass thru gpu
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet intel_iommu=on iommu=pt pcie_acs_override=downstream,multifunction initcall_blacklist=sysfb_init video=simplefb:off video=vesafb:off video=efifb:off video=vesa:off disable_vga=1 vfio_iommu_type1.allow_unsafe_interrupts=1 kvm.ignore_msrs=1 modprobe.blacklist=radeon,nouveau,nvidia,nvidiafb,nvidia-gpu,snd_hda_intel,snd_hda_codec_hdmi,i915"' # noqa: yaml[line-length]
    mode: '644'
    state: present
    create: true
  register: grub
  notify:
    - Update grub
    - Reboot

- name: Create vfio.conf
  ansible.builtin.copy:
    dest: /etc/modules-load.d/vfio.conf
    mode: "0644"
    content: |
      vfio
      vfio_iommu_type1
      vfio_pci
      vfio_virqfd
  notify:
    - Update initramfs
    - Reboot
