- name: SAMBA | Add samba
  ansible.builtin.apt:
    name: samba
    update_cache: true

- name: Add smb configuration
  ansible.builtin.template:
    src: smb.j2
    dest: "/etc/samba/smb.conf"
    backup: true
    mode: "0644"

- name: Restart samba
  ansible.builtin.systemd_service:
    state: restarted
    name: smbd
